### ISSUE TITLE
diff is empty but coverage changed

### ISSUE THREAD

**Issue by kmike** [codecov/support#101]
Hey,

Why are there no code changes and coverage diff is empty, but coverage % is changed: https://github.com/scrapinghub/splash/pull/322?

**Comment by stevepeak** [comment]
There are two different viewing method on coverage: 
1. **Diff: w/ coverage** which is what you can see on Codecov commit/compare views
  - This only expresses the Github Diff overlaid with coverage. For example if adjust a test or parameters but lines of code that are measured then this view will be empty (as you are experiencing)
2. **Compare Coverage** (which is being worked on now) is a way to compare reports and find which what lines changed in coverage. This is a much trickier report since Codecov has to account for the adjusted lines in each file to accurately express coverage. This feature will be coming out soon. Thank you!
