### ISSUE TITLE
Ruby empty files

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#133]
> http://www.rubydoc.info/gems/simplecov/SimpleCov/Configuration:track_files
> https://app.intercom.io/a/apps/nxdkbgzj/inbox/steve@codecov.io/conversations/1925399355
> @vegantech

Example file that gets skipped, but needed to be tracked

```
{
  "coverage": {
    "filename.rb": [null, 0, 0, 0, 0, ..lots of zeros.., 0, 0]
    ]
  }
}
```
> For this example keep in mind Ruby marks empty lines as a miss.

**Comment by vegantech** [comment]
I tried modifying the codecov-ruby gem so it produces the following:


all null
```
{
  "coverage": {
    "filename.rb": [null, null, null]
    ]
  }
} 

```
as well as 

an empty array
```
{
  "coverage": {
    "filename.rb": []
    ]
  }
} 

```
But both times, the file was ignored, so some change will be needed server side.   If there's a preferred format to make that server change easier, let me know and I'll make a pull request to update the codecov-ruby gem.

For my problem, if it were possible to adjust the logic of unifying the results so that when a line is reported as skipped (null) in one parallel build, but missed (0) in another, that they remain skipped (null)  instead of considered missed (0)

**Comment by stevepeak** [comment]
This will be a tricky one to fix because of lack of context. In both examples (zeros or nulls) there is no context for a line being a real line or an empty line (not tracked line).

The solution to this issue (from my first impression) has two logic points:

1. If the file is measured measures by another build and the context of the file is provided then a file without context can be reduced accordingly.
2. If the a file is provided with no context (as in these examples) then it will be considered entirely missed, where ever line is missed irregardless of context.

**Comment by vegantech** [comment]
That seems like it would work.    I ended up using a different approach (requiring all code files from my tests) instead of using Simplecov.track_files.    This unified properly across the parallel builds.

**Comment by stevepeak** [comment]
> requiring all code files from my tests

I like this approach :+1:
I've added a little caveat about this: https://github.com/codecov/codecov-ruby/blob/master/README.md#caveat

**Comment by stevepeak** [comment]
This issue was fixed about 2 weeks ago. 👍
