### ISSUE TITLE
Invalid (404) link in email notification

### ISSUE THREAD

**Issue by damianszczepanik** [codecov/support#138]
Emails are sent with delay and/or invalid content.

For damianszczepanik/cucumber-reporting/pull/346 I've received email (attached) which as you see has link to https://codecov.io/github/damianszczepanik/cucumber-reporting/commit/1159a90289584c49f0dc67e0bd26c17a772798dd that reports to me 404

It also shows diff result https://codecov.io/github/damianszczepanik/cucumber-reporting/compare/5a89fffdf1e6f342ac550b3baa6257b952870e24...1159a90289584c49f0dc67e0bd26c17a772798dd as 404 and diff coverage as  -0.30% which I believe is not true

**Comment by damianszczepanik** [comment]
[email.txt](https://github.com/codecov/support/files/150052/email.txt)

**Comment by damianszczepanik** [comment]
What is more I'm getting such invalid emails quite often.

**Comment by xh3b4sd** [comment]
I have a quite similar issue with the emails. I got this by mail and wondered. 
<img width="562" alt="screen shot 2016-03-24 at 04 25 45" src="https://cloud.githubusercontent.com/assets/552769/14007636/d4adb210-f178-11e5-96f4-e82b8131cd1d.png">

I wondered because I did nothing to the code. The pull request notification indeed looks like this. 
<img width="791" alt="screen shot 2016-03-24 at 04 27 17" src="https://cloud.githubusercontent.com/assets/552769/14007646/ed2ab518-f178-11e5-8643-103153db21a1.png">

So it looks like in my case the email notification used a 12 day old commit to compare. Something is fishy here.

**Comment by stevepeak** [comment]
@xh3b4sd The emails are always the original post. Codecov updates the comment so naturally the email will be outdated upon new commit. Is that the issue in your comment above>

**Comment by xh3b4sd** [comment]
I think I understand what is usually in the mail and that the PR comment is updated. Anyway, when I create a PR and the mail refers to a different commit than the PR is about, then this is a bug. Here the first PR comment and the mail information did not match.

**Comment by stevepeak** [comment]
@xh3b4sd curious: is the link in the your mail a merge commit?

**Comment by xh3b4sd** [comment]
No it was not. It was some intermediate commit of some pull request. The thing is, I squash all commits together before merging. Thus the commit of the mail yesterday does not even exist anymore. Nevertheless codecov refers to it and it looks like when knowing the commit hash it is still possible to view the commit state in github.
