### ISSUE TITLE
codecov not showing my master branch

### ISSUE THREAD

**Issue by vinniefalco** [codecov/support#285]
Its been 2 days now and the master branch still isn't showing up even though I've pushed to it. The other branches are all working great:
https://codecov.io/gh/vinniefalco/NuDB/branches
https://github.com/vinniefalco/NuDB/tree/master

**Comment by stevepeak** [comment]
Hey @vinniefalco for some reason the commits are showing up on the `develop` branch. I'm investigating why. Thank you for your patience

**Comment by stevepeak** [comment]
I believe this issue is because Codecov does not yet recognize branch merges without being within a pull request. So when you commit to your develop branch and merge without a pull request Codecov does not update the branch of that commit. 

We are working on supporting this behavior very soon. It's proven to be a little tricky to keep in sync with Github repo considering commits can be removed and change branches without Codecov receiving notice of this.

**Comment by vinniefalco** [comment]
Will deleting and recreating the project on codecov fix it?

**Comment by vinniefalco** [comment]
Also, I've been using an identical workflow for Beast, and codecov had no trouble with it:
https://github.com/vinniefalco/Beast
https://codecov.io/gh/vinniefalco/Beast/branches

**Comment by stevepeak** [comment]
Hum... I don't see any noticeable differences in the setup of these two projects that would impact this issue. 

Looking at https://codecov.io/gh/vinniefalco/NuDB/commit/6c871975d91f6b93da82ae22ebfcb0c2199b7273/builds

The first build is 27.1 (`branch=develop`) and the second is 28.1 (`branch=master`).

<img width="911 " alt="screen shot 2016-08-28 at 8 04 20 am" src="https://cloud.githubusercontent.com/assets/2041757/18033541/10edd14e-6cf6-11e6-824a-f057607d3eff.png">

The issue is Codecov does not change the branch from develop to master (this is under development).

----

The CI workflow in Beast looks different: https://travis-ci.org/vinniefalco/Beast/builds

**Comment by vinniefalco** [comment]
I had changed the NuDB default branch to develop for a little while, then back to master. Could that have something to do with it? I need to get the badge on my README.md working so what should I do? Should I just point the badge to the develop branch? Should I change the default branch? What would deleting my codecov repo and re-creating it do (can it be recreated after a delete)? Thanks

**Comment by stevepeak** [comment]
Today I deployed a patch to update commits upon `push` webhooks. That should clean this issue up and help keep the repos more in sync. 👍
