### ISSUE TITLE
Overview and bagde is not updating

### ISSUE THREAD

**Issue by jongpak** [codecov/support#286]
After I amended an already pushed commit and I pushed  with --force option, Overview and badge is not updating. but, reports is still updating.

**Codecov's master is c8e3b5e**
https://codecov.io/gh/jongpak/prob-framework
![image](https://cloud.githubusercontent.com/assets/15353893/18031612/89f37af8-6d23-11e6-9d53-3303f8aff0e6.png)

**but my repo's master is  8e452ba**
repo url: https://github.com/jongpak/prob-framework
https://codecov.io/gh/jongpak/prob-framework/commits

![image](https://cloud.githubusercontent.com/assets/15353893/18031622/341a9444-6d24-11e6-91a0-5bf2fa2e4125.png)

What is the problem..?

**Comment by stevepeak** [comment]
Nice job providing all the details here 👍 

The issue is that all the commits between "codecov master" and "my repos master" have the exact same timestamp "2016-08-28 01:17:45". So when codecov received these commits it would have checked to see which commit is the newest by `new.timestamp  > old.timestamp`

What may need to change is `new.timestamp >= old.timestamp` to fix force pushing. I'll review this more. Meanwhile I've update your head of branch manually.

**Comment by jongpak** [comment]
thank you :)
