### ISSUE TITLE
private repo not shown

### ISSUE THREAD

**Issue by aeyakovenko** [codecov/support#310]
Hi,

We have an account we created for codecov.io for our private repo's.  I can see the codecov coverage for private repos only when logged into that account `github@mesosphere.io`, but not from any one else's account on our team.

https://codecov.io/gh/mesosphere/tcp_metrics

Anatoly

**Comment by stevepeak** [comment]
@aeyakovenko sorry for the delay.

This may be a case where the user did not grant Codecov private repository access. When they access the project in Codecov via the url above they should get a warning saying that they must grant Codecov extra permissions to view the project.

Let me know if that helps out. Thank you!

**Comment by stevepeak** [comment]
Closing due to likely user related error. Please make sure the users are logged into Codecov with private repo access: https://codecov.io/login/github?private=t

**Comment by ryanhiebert** [comment]
I keep hitting these, for the past several weeks. Whenever I do, I have to go find this link again to enable private scope, because, coming from a link to the repository from a GitHub comment, the authorization on Chrome Ubuntu 16.04 seems to not take me to the GitHub authorization for private scope.

On mobile it works alright, though it logs me into GitHub, then tells me I don't have access and suggests I may need to enable private scope as well. I don't even get that much on the desktop.

**Comment by stevepeak** [comment]
Hey @ryanhiebert sorry for the confusion. We need to provide a more transparent login process so customers know if they are logging in with a private or public scope.
The only way to track if a user logs in with public or private is through cookies.

**Comment by ryanhiebert** [comment]
I'd be plenty happy if the desktop version gave the link to login with private scope the way the mobile version did. No need to remember it necessarily, I just want it to be possible without having to go track down an obscure URL when things aren't working.
