### ISSUE TITLE
Pull Request Comments not working

### ISSUE THREAD

**Issue by RyanCopley** [codecov/support#4]
![screen shot 2015-05-15 at 5 52 44 pm](https://cloud.githubusercontent.com/assets/819591/7662512/33737c3e-fb2b-11e4-8ee6-4759006b3f8e.png)

https://github.com/BlockSync/BlockSync/pull/10

It doesn't seem as if Codecov is posting comments to the PR, nor setting the status

**Comment by stevepeak** [comment]
I need to write some documentation on this, but what happens is the following:
1. Commit pushed to Github
2. CI triggered
3. Reports uploaded to Codecov
4. Codecov will search for a PR related to the sha
  a. results in 404 because pr not created yet.
5. ...3 minutes later... PR created (Codecov does not know..)

Right now the PR must be open at the time report is uploaded. I'm thinking of ways to improve this process. Ideas?

**Comment by RyanCopley** [comment]
What I'm understanding is happening is:

* Commit pushed to GitHub
* PR is made
* CI is triggered
* Reports uploaded to Codecov
* ??? The PR should exist

**Comment by stevepeak** [comment]
Actually that should work. And I think I figured out why. The merge commit is not real so it will never be found. I should use the actual PR number reported by the uploader.

I'll patch this up.

------
#### Notes

- [travis build][1] 
- Merge sha [`f08bbcf`][2]
- Actual sha [`bc83303`][3]

[1]: https://travis-ci.org/BlockSync/BlockSync/builds/62765217
[2]: http://codecov.io/github/BlockSync/BlockSync?ref=f08bbcfa27fc77827c31139af42b336d00bb71ca
[3]: https://github.com/BlockSync/BlockSync/pull/10

**Comment by stevepeak** [comment]
I've patched the server to now check for Pull Requests after the PR-CI to Travis. So this should be fixed up. Thanks!
