### ISSUE TITLE
Coverage is the ratio of hits / (sum of hit + partial + miss)

### ISSUE THREAD

**Issue by elharo** [codecov/support#444]
On https://docs.codecov.io/docs/about-code-coverage I see

Coverage is the ratio of hits / (sum of hit + partial + miss)

This is unclear. I initially read this as:

Coverage is the ratio of hits / ((sum of hit) + partial + miss)

and was confused but eventually figured out that you meant

Coverage is the ratio of hits / (sum of (hit + partial + miss))

Second, I am unsure that this is the right calculation. It depends on how partials are counted. Suppose we have an `if (x < 7)` line. How much does that contribute to the numerator and denominator when only one branch is tested? I.e. is it 1 hit, 1 miss (total 2) or one partial (total 1)? If it's one partial and no hits, it seems like you could get 0 coverage on something that really deserves 50% coverage (especially relevant for codecov.patch github hooks), but in either case the docs are fuzzy here.

**Comment by stevepeak** [comment]
Thank you for asking. I'll update the docs but the equation is `hits / (hit + partial + miss)`.

> How much does that contribute to the numerator and denominator when only one branch is tested?

Codecov is not responsible for collecting the coverage data, it is responsible in reporting it. Each language had it's unique way of collecting metrics, each language is also quite different in how it approaches branches (if at all). I cannot answer this question because it's language specific. *Codecov reports exactly what is uploaded*.
