### ISSUE TITLE
Record an "In Progress" Commit Status

### ISSUE THREAD

**Issue by dstufft** [codecov/support#67]
It appears that right now codecov does not touch the commit status until after all the other checks have ran, and then it registers either a fail or a success. However this means that I need to pay attention to how many checks have ran to make sure that codecov has successfully checked a PR. It would be better if instead codecov would immediately register an "in progress" commit status for it's check so that the merge button doesn't turn green until codecov has given the go ahead.

**Comment by stevepeak** [comment]
@dstufft this is a great suggestion. I was thinking the same thing the other day, however, the only issue I came in to was this: currently we submit features when all the CI builds pass (this ensures accurate data) in the case here I would need to set the "pending" Codecov statuses to "failed" when any of the CI builds, I'm unsure how others think of that. Lets review these examples below:

### Example 1
1. First build (1/2) finish
1. Codecov gets coverage report
  1. Codecov makes pending status
1. Second build finishes (2/2), and all CI is successful
1. Codecov sets status to success (given coverage data passes)

### Example 2
1. First build (1/2) finish
1. Codecov gets coverage report
  1. Codecov makes pending status
1. Second build finishes (2/2), and one or more CI was a failure
1. Codecov sets status to **failure** with description `All CI test must pass first` (or something like that)

## Questions
- Does a **failed** Codecov make sense for Example 2?
  - What should the message be for a failure due to CI not completed?

Thanks!

**Comment by dstufft** [comment]
I think that codecov shouldn't worry about whether or not the tests pass, but should only fail if the percentage is wrong.

**Comment by dstufft** [comment]
Also, it might make sense to instead of triggering when the first build finishes, to make it possible to have Github/etc ping codecov directly to expect builds? I'm not sure though.

**Comment by dstufft** [comment]
Oh, one other possible thing, instead of a failure is to record an error. This will show up as grey instead of  red and is generally used to say that this particular check didn't fail, but that there was some sort of error that occured in trying to do this check. In that case the second option might make sense if it uses an error instead of a failure.

**Comment by stevepeak** [comment]
> Github/etc ping codecov directly to expect builds

Receiving a payload from GH is simple and a practical option to initiate a pending status. However extra setup steps for integration with Codecov. In the future I'll revisit this.

> instead of a failure is to record an error

Brilliant! I do agree this makes more sense to use a "error" instead. I was looking for a way to avoid people thinking Codecov reported incorrectly when there was missing coverage reports (due to failed builds) that were the root cause.

----- 

I'm cleaning up the notifications this week and will have pending statuses added. You can expect this to be deployed shortly. I'll ping you when its deployed :+1:

**Comment by stevepeak** [comment]
@dstufft this has been deployed! Thank you for the suggestion and let me know if it behaves in the manner you expect. Cheers!
