### ISSUE TITLE
weird -0%-0%-0%-0% message 

### ISSUE THREAD

**Issue by kmike** [codecov/support#73]
I'm using codecov Firefox extension. This is what is displayed at https://github.com/scrapy/parsel/pull/19:

![screenshot](https://cloud.githubusercontent.com/assets/107893/9442593/15df9576-4a96-11e5-87a9-61acaf2f4a29.png)

**Comment by kmike** [comment]
After several page reloads the message disappeared; I can't get it now.

**Comment by stevepeak** [comment]
Thanks for reporting this. I recently saw this as well, which I believe was
due to the pjax event listener not clearing the display properly. I'll look
into a fix shortly.

On Monday, August 24, 2015, Mikhail Korobov <notifications@github.com>
wrote:

> After several page reloads the message disappeared; I can't get it now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codecov/support/issues/73#issuecomment-134228671>.
>


-- 
CEO/Founder of Codecov
Continuous code coverage.
@codecov

**Comment by stevepeak** [comment]
This has been fixed and deployed in recent extension changes. Thank you!

**Comment by kmike** [comment]
Thanks @stevepeak!
