### ISSUE TITLE
Github API Hooks

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#84]
Adding a Github API hook for repositories will fix the following:

1. **Condition** Commit is processed by Codecov *before* a pull request is created. **Issue** no comment or patch coverage will be posted. **Hooks** will post to Codecov when new pull requests are created and Codecov can post the features accordingly on the new pull request.
2. When branches are deleted Codecov can remove them from the UI (this already happens in our backend, but upon new uploads and not immediately)

**Comment by samuelcolvin** [comment]
Look reasonable.

I think there might be another related issue that if the pull request was not created when the first commit is processed: Then the reference commit for coverage comments (created after further commits are processed and the pull request does exist) is wrong, it uses `master > HEAD` instead of `merge-base`.
